export ZSH=$HOME/.oh-my-zsh
~/.dotfiles/roles/zsh/files/template.sh

ZSH_THEME="agnoster"


COMPLETION_WAITING_DOTS="true"

ZSH_CUSTOM=$HOME/roles/zsh/custom

plugins=(archlinux docker docker-compose git thefuck yarn)

# User configuration
export GOPATH=$HOME/.go
export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:$HOME/.dotfiles/bin:$GOPATH/bin"

source $ZSH/oh-my-zsh.sh

GOOGLE_SDK="docker run --rm=true -ti -v $HOME:/root --volumes-from gcloud-config google/cloud-sdk "

#aliases
alias ls="exa --git --time-style=long-iso --group"
alias vi=vim
alias fehg="feh -g 1920x1080 -d -S filename "
alias docker="sudo docker"
alias gcloud="$GOOGLE_SDK gcloud "
alias kubectl="$GOOGLE_SDK kubectl " 

#ls colors
eval $(dircolors -b .dircolors)
