export ZSH=$HOME/.oh-my-zsh

BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

ZSH_THEME="agnoster"


COMPLETION_WAITING_DOTS="true"

ZSH_CUSTOM=$HOME/roles/zsh/custom

plugins=(archlinux,git,docker,docker-compose,zarn)

# User configuration

  export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"

source $ZSH/oh-my-zsh.sh

#aliases
alias ls="ls --color=auto"
alias vi=vim

#ls colors
eval $(dircolors -b .dircolors)

