ZSH=$HOME/.oh-my-zsh

BASE16_SHELL_SET_BACKGROUND=false
~/.zsh_color_theme.sh
ZSH_THEME="agnoster"

COMPLETION_WAITING_DOTS="true"

REPORTTIME=10
plugins=(archlinux docker docker-compose thefuck zsh-syntax-highlighting)

# User configuration
export GOPATH=$HOME/.go
export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:$HOME/.dotfiles/bin:$GOPATH/bin:$HOME/.local/bin"
export EDITOR=vim

export MAVEN_OPTS=-Xmx2048m

export PATH="$PATH:$HOME/.node_modules/bin"
export npm_config_prefix=~/.node_modules

source $ZSH/oh-my-zsh.sh

#aliases
alias ls="exa --git --time-style=long-iso --group"
alias vi=vim
alias fehg="feh -g 1920x1080 -d -S filename "
alias docker="sudo docker"
alias docker-compose="sudo docker-compose"

#ls colors
# eval $(dircolors -b .dircolors)

eval $(keychain --eval --quiet id_rsa)

source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

if [ -f /usr/local/bin/kubectl ]; then source <(kubectl completion zsh); fi

s_whichhostgroup() {
    ldapsearch "(nisNetgroupTriple=\($1*)" nisNetgroupTriple 2>>/dev/null | grep "dn: "
}

eval "$(direnv hook zsh)"
copy3d() {
    DATA_DIR=$1
    MOUNT_DIR=/mnt/stick
    STICK_DIR=$MOUNT_DIR/prints/

    if [ "S1" = "" -o "$2" = "" ]; then
      echo "Missing parameter:"
      echo "copy3d folder_with_ctb_files /dev/sdXX"
      return 1
    fi

    sudo mount $2 $MOUNT_DIR

    for i in $(find $DATA_DIR -name "*.ctb"); do
        ls "$STICK_DIR/$(basename $i)" > /dev/null 2>&1
        if [ "$?" -ne "0" ]; then
            cp "$i" $STICK_DIR/
            echo "copied $(basename $i)"
        fi
    done

    sudo umount $MOUNT_DIR
    sync
    echo "\e[1mDone, remove USB Stick\e[7"
}
