---
- name: Install redshift
  pacman:
    name: redshift
    state: present
  become: yes

- name: Create redshift config folder
  file:
    path: "{{ ansible_env.HOME }}/.config/redshift"
    recurse: yes
    state: directory

- name: Add redshift config
  template:
    dest: "{{ ansible_env.HOME }}/.config/redshift/redshift.conf"
    src: redshift.conf.j2

- name: Create redshift systemd d folder
  file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user/default.target.wants/redshift.service.d"
    state: directory
    recurse: yes

- name: Add xrandr env vars for redshift
  copy:
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/default.target.wants/redshift.service.d/10-xenv.conf"
    src: xenv.conf

- name: Install redshift service
  systemd:
    name: redshift
    daemon_reload: yes
    state: started
    scope: user
    enabled: yes
