- include_tasks: arch.yml
  when: ansible_os_family == "Archlinux"
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Create mutt config
  template:
    src: "mutt.j2"
    dest: "{{dotfiles_user_home}}/.mutt_{{item.id}}"
  with_items: "{{ emails }}"

      

