---
- name: Install mutt with pacman
  pacman:
    name: mutt
    state: present
  become: yes

- name: Create mutt config
  template:
    src: "mutt.j2"
    dest: "{{ ansible_env.HOME }}/.mutt_{{item.id}}"
  with_items: "{{ mutt_accounts }}"
  no_log: yes
  loop_control:
    label: "{{ item.id }}"
