- name: Collecting Facts
  hosts: desktop
  gather_facts: yes

- name: Set up local environment
  hosts: desktop
  roles:
    - base
    - git
    - ssh_client
    - package_manager
    - google-cloud
    - { role: zsh, tags: [ "theme" ] }
    - { role: windowmanager, tags: [ "theme" ] }
    - redshift
    - filemanager
    - vim
    - mutt
    - irssi
    - pulseaudio
    - intellij
