---
- name: Set up local environment
  hosts: desktop
  roles:
    - base
    - git
    - ssh_client
    - package_manager
    - google-cloud
    - zsh
    - windowmanager
    - filemanager
    - vim
    - mutt
    - irssi
    - pulseaudio
#    - intellij
