- name: Collecting Facts
  hosts: zero scraps betelgeuse
  gather_facts: yes

- name: Set up local environment
  hosts: zero scraps betelgeuse
  vars_files:
      - 'vars/vault.yml'
      - 'vars/vars.yml'
      - 'vars/git_private.yml'
  roles:
    - git
    - {role: package_manager, tags: ['bootstrap']}
    - {role: zsh, tags: ['bootstrap']}
    - i3
    - vim
    - ag
    - mutt
    - cloc
    - irssi
