- name: Collecting Facts
  hosts: desktop
  gather_facts: yes

- name: Set up local environment
  become: yes
  hosts: desktop
  roles:
    - git
    - package_manager
    - google-cloud
    - zsh
    - windowmanager
    - filemanager
    - vim
    - mutt
    - irssi
    - pulseaudio
    - ide
