- name: Collecting Facts
  hosts: desktop
  gather_facts: yes

- name: Set up local environment
  become: yes
  hosts: desktop
  roles:
    - git
    - {role: package_manager, tags: ['bootstrap']}
    - zsh
    - windowmanager
    - filemanager
    - vim
    - mutt
    - irssi
    - pulseaudio
    - ide
