- name: Collecting Facts
  hosts: desktop
  gather_facts: yes

- name: Set up local environment
  hosts: desktop
  roles:
    - git
    - {role: package_manager, tags: ['bootstrap']}
    - zsh
    - i3
    - vim
    - ag
    - mutt
    - cloc
    - irssi
