- name: Collecting Facts
  hosts: remote
  gather_facts: yes

- name: Set up remote dev environments (clone)
  hosts: remote
  tasks:
    - name: Clone dotfiles repo
      git:
        repo: https://github.com/gidsi/dotfiles.git
        dest: "{{dotfiles_user_home}}/.dotfiles"

- name: Set up remote development environments (roles)
  hosts: remote
  roles:
    - git
    - zsh
    - vim
