- name: Install irssi with pacman
  pacman: name=irssi state=present
  become: yes

- name: Create irssi config folder
  file:
    path: "{{ ansible_env.HOME }}/.irssi"
    state: directory

- name: Create irssi config
  template:
    src: "irssi.j2"
    dest: "{{ ansible_env.HOME }}/.irssi/config"
