- include: arch.yml
  when: ansible_os_family == "Archlinux"
- include: debian.yml
  when: ansible_os_family == "Debian"

- name: Create irssi config
  template:
    src: "irssi.j2"
    dest: "{{dotfiles_user_home}}/.irssi/config"
