---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: archlinux-python:latest
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_LIBRARY: ../../../../library
verifier:
  name: ansible
