#!/bin/bash

PICTURE_PATH=~/.dotfiles/roles/i3/screenlock/pictures
RANDOM_IMAGE=$PICTURE_PATH/$(ls $PICTURE_PATH | shuf -n 1)
RESOLUTION=$(xrandr -q | awk -F'current' -F',' 'NR==1 {gsub("( |current)","");print $2}')
RES_MAX=$(expr match $RESOLUTION '\(.[0-9]*\)')

screencapturelock() {
  cd /tmp
  scrot lock.png
  convert lock.png -blur 5x5 lock.png
  composite ~/.dotfiles/roles/i3/screenlock/chaospott.png lock.png lock.png
  #frosted -b 5 -s 5 lock.png lock.png
  i3lock -uef -i lock.png
  rm lock.png
}

resizepicturelock() {
  cd /tmp
  convert $PICTURE_PATH/$(ls $PICTURE_PATH | shuf -n 1) -resize $RES_MAXx$RES_MAX -gravity Center -crop $RESOLUTION lock.png
  if [ -a lock-1.png ]; then
      mv lock-1.png lock.png
  fi
  i3lock -uef -i lock.png
  rm lock-*.png
}

case "$1" in
  picture)
    resizepicturelock
    ;;
  *)
    i3lock -uef -i $PICTURE_PATH/$(ls $PICTURE_PATH | shuf -n 1)
esac

exit 0
