- name: Install packages
  pacman:
    name: [
      'i3-wm',
      'i3lock',
      'imagemagick',
      'rofi',
      'i3status',
      'rxvt-unicode',
      'compton',
      'feh',
      'scrot',
      'ttf-font-awesome',
      'xorg-xrandr',
      'xorg-xbacklight',
      'wpa_actiond'
    ]
    state: latest
  become: true

- name: Create screenshot folder
  file:
      path: ~/screenshots
      state: directory

- name: Install from aur
  aur:
    name:
      - unclutter-xfixes-git
      - ttf-hack-powerline-git
      - clipster-git
      - urxvt-resize-font-git
      - google-chrome-dev
  become_user: aur_builder
  become: true

