- name: Install packages
  pacman:
    name:
      - i3lock
      - imagemagick
      - i3status
      - compton
      - feh
      - scrot
      - ttf-font-awesome
      - acpilight
    state: present
  become: true

- name: Install from aur
  aur:
    name:
      - i3-gaps
      - unclutter-xfixes-git
      - powerline-fonts-git
      - clipster-git
      - wpa_actiond
      - google-chrome-dev
      - autorandr
  become_user: aur_builder
  become: true

- name: Create screenshot folder
  file:
    path: "{{ ansible_env.HOME }}/screenshots"
    state: directory

- name: Ensure there is a ~/.config/i3 folder
  file:
    path: "{{ ansible_env.HOME }}/.config/i3"
    state: directory
    recurse: yes

- name: Copy background and screenlock
  copy:
    src: files/screenlock
    dest: "{{ ansible_env.HOME }}/.config/i3/"

- name: Read i3 color file
  slurp:
    src: "{{ ansible_env.HOME }}/.base16colors/templates/i3/colors/base16-{{ theme }}.config"
  register: i3BaseColorBase64
  tags:
    - theme

- name: Copy i3 config
  template:
    src: i3config.j2
    dest: "{{ ansible_env.HOME }}/.config/i3/config"
  vars:
    i3BaseColor: "{{ i3BaseColorBase64['content'] | b64decode }}"
  tags:
    - theme

- name: Install Py3status
  aur:
    name: py3status-git
  become_user: aur_builder
  become: yes

- name: Create i3status
  template:
    src: i3status.j2
    dest: "{{ ansible_env.HOME }}/.i3status.conf"

- name: Link dircolors
  copy:
    src: dircolors
    dest: "{{ ansible_env.HOME }}/.dircolors"

#- name: Link zlogin
#  copy:
#    src: zlogin
#    dest: "{{ ansible_env.HOME }}/.zlogin"

- name: Copy brightness script
  copy:
    src: brightness
    dest: "/usr/local/bin/brightness"
    mode: 0755
  become: true

- name: Copy volume script
  copy:
    src: volume
    dest: "/usr/local/bin/volume"
    mode: 0755
  become: true

- name: Enable wireless auto
  systemd:
    name: netctl-auto@{{ wlan_device }}
    enabled: yes
  when: wlan_device is defined
