wlan_device: "wlp4s0"
batteries: [ '/sys/class/power_supply/BAT0/uevent']
keyboard_layout: "us"
aur_installed: true
git_full_name: timm
git_email: "{{ vault_git_email }}"
git_signingkey: "EA94F9A9FA755BFFA365F0597F059C52F5F705F9"

theme: "dracula"
