
- name: Make sure zsh is installed
  pacman: name=zsh state=present
  become: true

- name: Install thefuck
  pacman: name=thefuck state=present
  become: true

- name: Install exa
  pacman: name=exa state=present
  become: true

- name: Install fzf
  pacman: name=fzf state=present
  become: true

- name: Install keychain
  pacman: name=keychain state=present
  become: true
