# Installation and setup
- name: Install packages
  pacman:
    name:
      - zsh
      - thefuck
      - exa
      - fzf
      - keychain
    state: present

- name: link zshrc
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/zshrc"
    dest: "{{ dotfiles_user_home }}/.zshrc"
    state: link

- name: Add Oh My Zsh
  git:
    repo: "https://github.com/robbyrussell/oh-my-zsh.git"
    dest: "{{ dotfiles_user_home }}/.oh-my-zsh"

- name: Add Oh My Zsh syntax highlighting
  git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "{{ dotfiles_user_home }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
