
# Installation and setup
- include: debian.yml
  when: ansible_os_family == "Debian"
- include: arch.yml
  when: ansible_os_family == "Archlinux"

# Configuration
- name: Check if zshrc already exists
  stat: path="{{dotfiles_user_home}}/.zshrc"
  register: zshrc_stat

- name: Back up zshrc if it exists
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: "{{dotfiles_user_home}}/.zshrc.bak"
  when: zshrc_stat.stat.exists

- name: Copy minimal zshrc
  copy: src=zshrc_minimal dest={{dotfiles_user_home}}/.zshrc
  when: not zsh_prezto
