# Installation and setup
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"
- include_tasks: arch.yml
  when: ansible_os_family == "Archlinux"

- name: link zshrc
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/zshrc"
    dest: "{{ dotfiles_user_home }}/.zshrc"
    state: link

- name: Add Oh My Zsh
  git:
    repo: "https://github.com/robbyrussell/oh-my-zsh.git"
    dest: "{{ dotfiles_user_home }}/.oh-my-zsh"
