- name: Install packages
  pacman: name={{ item }} state=latest
  become: true
  with_items:
    - i3-wm
    - imagemagick
    - rofi
    - i3status
    - rxvt-unicode
    - compton
    - feh
    - scrot
    - ttf-font-awesome

- name: Create screenshot folder
  file:
      path: ~/screenshots
      state: directory

- name: Install from aur
  aur: name={{ item }} user=gidsi dir=/tmp
  become: true
  with_items:
    - unclutter-xfixes-git
    - ttf-hack-powerline-git
    - clipster-git
    - urxvt-resize-font-git
