---
- name: Install git
  pacman:
    name: git
    state: present
  become: yes

- name: Link global gitignore file
  copy:
    src: "gitignore_global"
    dest: "{{ ansible_env.HOME }}/.gitignore_global"

- name: Configure git
  template:
    src: "gitconfig.j2"
    dest: "{{ ansible_env.HOME }}/.gitconfig"
