---
- name: Install ranger
  pacman:
    name:
      - ranger
      - w3m
    state: present

- name: Activate image preview in ranger
  lineinfile:
    path: "{{ ansible_env.HOME }}/.config/ranger/rc.conf"
    create: yes
    line: 'set preview_images true'
