---
- name: Run influx docker
  docker_container:
    name: influxdb
    image: influxdb
    state: started
    env:
      INFLUXDB_ADMIN_ENABLED: true
      INFLUXDB_ADMIN_USER: "{{ admin_user }}"
      INFLUXDB_ADMIN_PASSWORD: "{{ admin_password }}"
      INFLUXDB_USER: "{{ user }}"
      INFLUXDB_USER_PASSWORD: "{{ password }}"
      INFLUXDB_DB: "{{ db }}"
    published_ports:
     - "8086:8086"
    volumes:
     - "{{ influx_data_folder }}/data:/var/lib/influxdb"
     - "{{ influx_data_folder }}/influxdb.conf:/etc/influxdb/influxdb.conf:ro"
