---
- name: Create service config
  block:
  - copy:
      src: "influxdb.conf"
      dest: "{{ influx_data_folder }}/influxdb.conf"

  - file:
      path: "{{ influx_config_folder }}"
      state: directory
      owner: root
      group: root
      mode: 0755

  - template:
      src: env.j2
      dest: "{{ influx_config_folder }}/.env"
      owner: root
      group: root
      mode: 0700

  - copy:
      src: docker-compose.yml
      dest: "{{ influx_config_folder }}/docker-compose.yml"
      owner: root
      group: root
      mode: 0755

- name: Run influx
  docker_service:
    project_src: "{{ influx_config_folder }}"
    recreate: always
    build: yes
    nocache: yes
    state: present

