galaxy_info:
  author: gidsi
  description: installs and configures ssh client

  license: MIT

  min_ansible_version: 2.9
  platforms:
    - name: Archlinux
      versions:
      - all

  galaxy_tags: []

dependencies: []
