# Installation
- name: Install vim
  pacman:
    name: gvim
    state: present
  become: yes

# Plugin manager
- name: Makes sure autoload directory exists
  file:
    path: "{{ ansible_env.HOME }}/.vim/autoload"
    state: directory

- name: Configure vim
  copy:
    src: vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"

- name: Install plugins
  command: vim +PlugInstall +qall
  when: vim_install_plugins
